name: Crawl Dealmoon and Push to Strapi

on:
  schedule:
    - cron: '*/10 * * * *'  # Chạy mỗi 10 phút
  workflow_dispatch:        # Cho phép chạy thủ công từ GitHub UI

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Run crawler
        env:
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
        run: php Beauty.php
